id: hl7.fhir.fr.core.test
canonical: http://hl7.fr/fhir/fr/core/test
name: Test4FrCore
title: Tests pour l'IG FrCore
publisher:
  name: Interop'Santé
  url: http://interopsante.org/
contact:
  - name: InteropSanté
    telecom:
      - system: email
        value: fhir@interopsante.org
        use: work
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: ci-build
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters:  # see https://build.fhir.org/ig/FHIR/fhir-tools-ig/CodeSystem-ig-parameters.html
  shownav: 'true'
  pin-canonicals: pin-multiples # Avoid raising many warnings when there are no version for URLs. "pin-multiples": pinning the canonical reference will only happen if there is multiple versions found in the package dependencies
  path-expansion-params: 
    - ../../input/data/expansion-params.json # for using French SNOMED CT Extension

# The instanceOptions property is used to configure certain aspects of how SUSHI processes instances.
instanceOptions:
  setMetaProfile: always # Determines for which types of Instances SUSHI will automatically set meta.profile if InstanceOf references a profile
  setId: always # Determines for which types of Instances SUSHI will automatically set id if InstanceOf references a profile

dependencies:
  hl7.fhir.fr.core: dev

pages:
    index.md:
        title: Accueil
    downloads.md:
        title: Téléchargement du guide
menu:
    Accueil: index.html
    Ressources de conformité: artifacts.html
    Documentations: 
        Documentation des IGs: new-tab https://interop.esante.gouv.fr/ig/documentation/
        Site d'InteropSanté: new-tab https://www.interopsante.org/
        Téléchargements: downloads.html

#  logging:
#    - tx #tx: Messages describing the use of the terminology server (for debugging)
#    - html #html: Log when validating a html page (troubleshooting only - leave off)
#    - generate #generate: Log when producing an individual resource (troubleshooting only - leave off)
#    - init #init: Messages describing the start up process (for debugging)
#    - progress #progress: Overall progress messages
